#= require cardboard/wysihtml5-0.4.0pre 

$(document).on 'page:load', ->
  window['rangy'].initialized = false
  return
wysihtml5ParserRules = tags:
  'b': {}
  'i': {}
  'br': {}
  'ol': {}
  'ul': {}
  'li': {}
  'h1': {}
  'h2': {}
  'h3': {}
  'blockquote': {}
  'u': 1
  'img': 'check_attributes':
    'width': 'numbers'
    'alt': 'alt'
    'src': 'url'
    'height': 'numbers'
  'a':
    set_attributes: target: '_blank'
    check_attributes: href: 'href'
  'span': 1
  'div': 1
  'code': 1
  'pre': 1
page_links_template = link: ->
  gon.rich_text_links_modal
rich_text_editor_defaults = 
  'image': false
  'customTemplates': page_links_template
  'parserRules': wysihtml5ParserRules
  'useLineBreaks': false
  'font-styles': false
$(document).on 'ready page:load', (e) ->
  if $('.wysihtml5').length
    $('.wysihtml5').wysihtml5 rich_text_editor_defaults
    $('iframe.wysihtml5-sandbox').wysihtml5_size_matters()
    # TODO: find a better way to handle multiple RTE on a single page
    $('.bootstrap-wysihtml5-insert-link-modal .tab-content div').each (index) ->
      $(@).attr 'id', $(@).attr('id') + index.toString()
      return
    $('.bootstrap-wysihtml5-insert-link-modal .nav li a').each (index) ->
      $(@).attr 'href', $(@).attr('href') + index.toString()
      if index % 3 == 0
        $(@).tab 'show'
      return
    # END TODO
  return
$(document).on 'cocoon:after-insert', (e, insertedItem) ->
  if $(insertedItem).find('.wysihtml5').length
    $(insertedItem).find('.wysihtml5').wysihtml5 rich_text_editor_defaults
  return
$(document).on 'click', '.bootstrap-wysihtml5-insert-link-modal .link_pages a', (e) ->
  e.preventDefault()
  console.log 'clicked'
  modal = $(@).closest('.bootstrap-wysihtml5-insert-link-modal')
  modal.find('input.bootstrap-wysihtml5-insert-link-url').val $(@).data('url')
  modal.find('#insert_link').click()
  return
$(document).on 'change', '.bootstrap-wysihtml5-insert-link-modal .tab-pane input', ->
  $(@).closest('.bootstrap-wysihtml5-insert-link-modal').find('.bootstrap-wysihtml5-insert-link-url').val $(@).val()
  return

# ---
# generated by js2coffee 2.0.1
